version: "3.9"

services:
  app:
    image: vfxalert/jtl-worker:latest
    restart: always
    environment:
      - PORT=80
      - STRATEGY_FILES_PATH=/www/app/strategy-files/
      - DATABASE_URL=file:/www/app/storage.db
      - MARKETS_FILE_PATH=/www/app/markets.json
      - ARTIFACTS_DIR_PATH=/www/app/artifacts
      - LOGS_DIR_PATH=/www/app/artifacts
      - HISTORY_BARS_PATH=/www/app/history-bars
      - HISTORY_BARS_URL=https://data.binance.vision/data/futures/um/monthly/klines
      - REDIS_URL=redis://redis:6379
    ports:
      - "${APP_PORT}:80"
    links:
      - redis
    volumes:
      - ./strategy-files:/www/app/strategy-files:cached
      - ./storage.db:/www/app/storage.db:delegated
      - ./history-bars:/www/app/strategy-files:delegated
      - ./markets.json:/www/app/markets.json
      - ./artifacts:/www/app/artifacts

  redis:
    image: redis:alpine
    restart: always
    